### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/isitweeka#17]
Create a mailing list pop-up.  Great way to get people coming back to the site, and makes it easier for us to make big announcements such as "we've launched a blog!"

**Comment by ILikeTeaALot** [comment]
I'm fine with a banner for this. but under _**NO**_ circumstances is a pop-up happening

**Comment by ILikeTeaALot** [comment]
a pop-up on mobile, if done correctly, could work.... no pop-ups on desktop though
