### ISSUE TITLE
Charity Events page/section

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/isitweeka#3]
Add a section to the site to advertise charity events.  At the basic, include a link to more information (such as the Eventbrite page).  Then, include past events, and advertising assets

I want to use this for Would I Lie To You.

Checklist:

- [x] Event header and section
- [x] Add WILTY
- [x] Add ability to add House Event & fundraisers
- [x] Optimise for mobile
- [x] Centre the "Next week is..."
- [x] Handling of past events
- [x] Add past events
- [ ] Add event dashboard for event info, like money raised, people who attended, text updates from organisers - see #12, not for this issue's PR.

**Comment by Gum-Joe** [comment]
Was thinking something like this:
![20201227_123537](https://user-images.githubusercontent.com/12299307/103170981-62586880-4840-11eb-9dbf-e5922b879a3e.jpg)


Have it be controlled by a JSON file, which has the PR image set by a URL to what is in public.

**Comment by ILikeTeaALot** [comment]
ad30c60 completes up to the layout and design.
Implementing a JSON based system to "automagically" handle event listing shouldn't be too hard

**Comment by Gum-Joe** [comment]
Past events (list such that most recent is first on the website):
- The Zoom Quiz - June 2020
- Weakest Link? - Unknown, say Spring 2020
- WILTY 2021 - January 2021
- Echo Dot Raffle - February 2020
- House Touch Rugy - Beaufort won. Autumn 2020.

Future events:
- House Cross Country - date unknown, but in progress.

**Comment by ILikeTeaALot** [comment]
I think for events that do not have a header image either something abstract and generic, or just put the event name in a different font maybe

**Comment by Gum-Joe** [comment]
Event name in a different font?

**Comment by Gum-Joe** [comment]
In terms of house events, what to include:
- Start date/term
- Event name
- Coming up, ongoing, done
- If ongoing/done, who winning/won?
- ?
