### ISSUE TITLE
R-Tab overlaps 'next week' text on mobile

### ISSUE THREAD

**Issue by Asametric** [Gum-Joe/isitweeka#62]
Device: Xiaomi Redmi Note 4X (1080 x 1920)
OS: Android 9.0/LineageOS 16.0
Browser: Chrome Mobile. 

Also occurs in Firefox on Windows 10 when window is made smaller in both x and y directions. I haven't tried with any other browsers.

When the banner alert is closed, the `r-tab`s at the top overlap with `h2.mobile`. 
I think that removing the `position: absolute` from `div.r-tab-row` would fix this issue.

**Comment by Gum-Joe** [comment]
Hi, thank you for raising this!

I'll have a look at this over the weekend (if I am lucky and have time, will open sooner on my PC and set the date back to check) to see if I can reproduce, and will bundle this as a fix into #56.

**Comment by Gum-Joe** [comment]
![image](https://user-images.githubusercontent.com/12299307/122644166-cc750a80-d10b-11eb-92f4-67ba790ed6a3.png)

Issue reproduced. Working on a fix....

**Comment by Gum-Joe** [comment]
Fix created, will be pushed to production when #56 is merged. (also apologies for delay of fixing, I had exams)
![image](https://user-images.githubusercontent.com/12299307/122644739-b3218d80-d10e-11eb-81fd-d07bebaa4797.png)
