### ISSUE TITLE
(CONSULTATION REQUIRED) Student Council Election System

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/isitweeka#8]
Provide an integration to the student council to:

- Allow students to SECURLY vote in elections
- Allow results to be counted, somewhat in real-time (with real-time displays)
- Allow the winner to be announced.]

CONSULT STUDENT COUNCIL FIRST,

**Comment by ILikeTeaALot** [comment]
https://youtu.be/LkH2r-sNjQs

**Comment by Gum-Joe** [comment]
Yes, I am aware electronic voting is a bad idea, but given the COVID-19 pandemic, in-person voting can't really occur (not safe, either for the voters and the counters).   Hence, an electronic voting system of sorts will be needed - and likely something custom, as otherwise, I guarantee you the SC will just use a Google Form, which means no-one can have anonymity when voting (bad!).

**Comment by Gum-Joe** [comment]
I should clarify that even if we CAN do in-person voting, we should do that instead - however, I'm assuming this will not be allowed, and I want to avoid a situation where e.g. Google Forms is used for the vote.

**Comment by Gum-Joe** [comment]
Ok so I checked, turn out Google Forms has an option to only allow one response from a user and not record emails BUT this also means our "trusted organisations" (i.e. the girls' school) will be able to vote in it with no way to differentiate - which means Google Forms is no longer viable as either anonymity or the scope of the electorate has to be compromised.

**Comment by Gum-Joe** [comment]
This exists: https://github.com/mdipierro/evote

**Comment by Gum-Joe** [comment]
@ILikeTeaALot We should discuss this, if we wish to proceed ahead we should then write a email to the SC informing them of possible options,

**Comment by ILikeTeaALot** [comment]
I'm no longer a student so I'll leave the email to you.

as for the evoting, that video was 100% joking. we're dealing with a student Council election and a school population, so there's not really _any_ stakes...

**Comment by Gum-Joe** [comment]
Ok.

Whilst what you say is true, these are always a matter of when, not if, and I know there is at least one member of the school who will try to bring down a voting system....

**Comment by Gum-Joe** [comment]
SC does not want a digital election system, closing as stale issue.
